```{r Librerias, echo=FALSE, include=FALSE}
rm(list = ls())
library(tidyverse)
library(readxl)
```

# Datos a utilizar

```{r Datos}

inflacion <- read_excel(path = "~/PES/Para la tesis/Tesis/Pass through/Datos/Datos.xlsx", 
                        sheet = "Inflación Guatemala", range = "A1:I403",
                        col_types = c("date", "numeric", "numeric", "numeric",
                                       "numeric", "numeric", "numeric",
                                       "numeric", "numeric"))

# Generando la columna que distingue los tipos de esquema de política monetaria

inflacion <- inflacion %>% mutate("Esquema" = case_when(Periodo < as.Date("2005-01-01") ~ "Agregados Monetarios",
                                  Periodo >= as.Date("2005-01-01") ~ "Metas de Inflación"))
```

# Gráfica de inflación y esquemas de política monetaria

```{r}

ggplot(data = inflacion, aes(x = Periodo, y = `Porcentual interanual`)) + 
  geom_line(aes(color = Esquema), size = 1.5) +
  geom_smooth(method = "loess" ,se = FALSE, color = "black", size = 1) +
  labs(y = "Porcentual", x = "") +
  
  theme_bw(base_size = 16) +
  
  scale_color_brewer(palette = "Set1") +
  
  theme(legend.title = element_blank(),
        legend.position = "bottom")

# En geom_smooth se agrego la linea de tendencia mediante
# una gregresión local (LOESS).

```

# Inflación Media según esquema de política

```{r Media de inflación}

# Considerando el pico de inflación hasta Enero 1991

inflacion %>% group_by(Esquema) %>% 
  summarise("media inflación" = mean(`Porcentual interanual`))

# Sin considerar el pico de inflación 
# Calculos desde enero 1992

inflacion[c(37:402),] %>% group_by(Esquema) %>% 
  summarise("media inflación" = mean(`Porcentual interanual`))

```


# Prueba Dickey-Fuller para el periodo EMEI

```{r}

# Prueba para el periodo EMEI
tseries::adf.test(inflacion$`Porcentual interanual`[c(193:402)])

```

# Gráfica del tipo de cambio
## Datos del tipo de cambio

```{r Datos tipo de cambio}

tc <- read_excel(path = "~/PES/Para la tesis/Tesis/Pass through/Datos/Datos.xlsx", 
                        sheet = "TC 1995-2022", range = "A1:K331")
```

# Gráfica evolución del tipo ce cambio 1995-2022
```{r Gráfica}

ggplot(data = tc, aes(x = periodo, y = `Promedio simple`)) +
  geom_line(size = 1.5) +
  ylim(c(4,9)) +
  labs(y = "Tipo de cambio", x = "") +
  theme_bw(base_size = 16) 

```



